language: node_js
node_js:
- '11'
deploy:
  provider: npm
  email: rickslabstudent@gmail.com
  api_key:
    secure: SMD7YqNrdHRlxxr/uKZxJN36Q9cX7yXrE3Pvahh6MrapZK+N2DFYNdE9F6vQv+vIHtBJGGh+1jI6cBB/UqDKpBq4gh9Ap8Ws2sCiuT55Dzvfw89+5UELBvo5Gzhl5kyPKNddYh7U5DXFAbqbzm5KMfMJAtySzpoBOV1Pz75hX2qqbQt3fWmQiDkUO/I5f5oHNxwvJh4hKhBDHBvr6T5rDScG+n5ZH3JpG8JdJE1nujDuJYRDbapDMf7Drcci5H21infAl2eQFLraQrCeWRQ2g8aYMfyLr0/Vnb79/avKX5Bc2b4OQNU9RyCVLBsRl1sIdbzQ4kX1PxMkydR+mt1ZdmjzTq4ZkFgL88Ks6JLoBntnM/vqkKv8VkQr9YmvtM55vrcdUOGTSgO+WRtd+AtdPQtWZm9orvQsMm1jvPmfpcOojMtgW3Fl67ew8UX4mzEfBM+gp3r6izNPVKuLKIFnBno8xel/lglnFcmcw2VEva4RvdsMYIMGTfYG4Z84QG0viqLK+MkeO+3rH31yGI3UoosZPdjtqxWpLduyctY+8h+EnSeN2ZR3Klb8Hns3Pn88xHaLqBrHBWgzOUVgI0jcglrC01MwUN0cjjm7Zlsld9ZwYPWV1U1D7P5WtzMzZe9nY8P7QEcT4aaOgThWpsUZBoGvss7nTqyO6iJ/YCnjImk=

