language: node_js
node_js:
- "11"

deploy:
  provider: script
  script: "cp .npmrc.travis $HOME/.npmrc && npm publish"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - chessler@unomaha.edu
    - bricks@unomaha.edu
    on_success: change
    on_failure: always
